apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    team: frontend
    version: 1.0.1
    environment: development
  annotations:
    description: ini adalah aplikasi yang dibuat oleh team frontend
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine
      ports:
        - containerPort: 80