apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label
  labels:
    team: backend
    version: 1.4.5
    environment: production
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine
      ports:
        - containerPort: 80