apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-name
spec:
  minReplicas: 3 # min replicas saat pertama kali deployment connect ke HPA
  maxReplicas: 5 # max replicas ketika traffic menyentuh metrics tertentu
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-name
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory # hati hati menggunakan memory, harus bisa manage memory dengan benar aplikasi nya
        target:
          type: Utilization
          averageUtilization: 70