apiVersion: v1
kind: ReplicationController
metadata:
  name: nama-replication-controller
  labels:
    label-key1: label-value1 
  annotations:
    annotation-key1: annotation-value1
spec:
  replicas: 3 # berapa jumlah pod yang mau dibuat
  selector: # untuk select pod , pastikan selector sama dengan label yang ada di pod
    label-key1: label-value1 
  template:
    metadata:
      name: nama-pod # nama pod akan ditambah unique code oleh replication controller
      labels:
        label-key1: label-value1
    spec:
      containers:
        - name: container-name
          image: image-name
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
